thesis_main.tex
Damit es auch funktioniert sauberen Quellcode einzubinden, müssen diese Farben noch definiert werden...
Die wurden bisher zwar in \lstset als commentstyle und stringstyle  aufgerufen, aber nirgends definiert...
Nun funktioniert es.
=> Added Colors for listinputs

skripte/modsBiblatex.tex
Online-Einträge wurden nun richtig definiert, so wie sie die FOM gerne hätte.
Als Jahr sollte das Erscheinungsdatum angegeben werden, als Note den Zeitpunkt des Aufrufes, Titel und URL sollten selbsterklärend sein.
=> Online Einträge definiert

kapitel/kapitel_2/kapitel_2.tex
In der PDF-Datei sollte nun der HTML-Quellcode eingebunden sein, durch meine vorherigen Pull-Requests. 
Bitte die neu generierte PDF Datei noch hochladen.
@andygrunwald
=> Added external Quellcode Listing

compile.sh
Wenn man das Bash Skript ausführt, während man in einem anderen Folder noch ist bzw vorher auf dem Terminal woanders hin navigiert hat, funktioniert nur pwd nicht. 
Diese Lösung hier funktioniert immer.
=> Run Bash File from this directory

.travis.yml
Hallo Andy,
ich habe mich an die Travis CI config gesetzt. Das kompilieren des Dokuments ist mit der neuen Konfiguration wieder möglich:
https://travis-ci.org/chilian/FOM-LaTeX-Template/builds/141555232
Mir gefällt noch nicht das 859 MB für jeden Test runter geladen werden müssen. Ggf. optimiere ich das noch um die Laufzeit beim Build zu minimieren.
VG
Christoph
=> fixes travis-ci config

README.md
Die Docker Kompilierung funktioniert nur, wenn der Docker-Befehl in dem Ordner ausgeführt wird, wo die Compile.sh liegt. Dies sollte man für Anfänger auf jedenfall noch dazu schreiben.  Zusätzlich habe ich beschrieben, wie man in Mac und Windows in den jeweiligen Ordner über das Terminal/Commandozeile kommt.
=> Docker-Kompilierung genauer beschreiben

README.md
Der docker Befehl klappte nicht unter Linux, wenn der Pfad Leerzeichen
enthielt, mit dieser Änderung sind auch diese Pfade jetzt valide.
=> fix docker Befehlszeile mit Leerzeichen

LICENSE
Es wird das aktuelle Jahr verwendet und ein Rechtschreibfehler in der LICENCE-Datei korrigiert.
=> Add current year to LICENCE and fix typo

README.md, kapitel/anhang/erklaerung.tex
Nur ein paar kleine Änderungen:
- Beschreibung zum ändern der Unterschrift angepasst
- Text für Windows Docker angepasst 
Ich habe mit einem Kommilitonen herausgefunden, dass die PowerShell wohl `${PWD}`  unterstützt, aber nicht den `cmd`-Befehl `%CD%`
=> Kleine Text Änderungen

skripte/modsBiblatex2018.tex
Die Felder DOI, issn, isbn, url und eprint werden nach FOM Leitfaden 2018 bei inproceedings nicht genutzt.
Für die Anzeige werden sie deshalb geleert.
=> Inproceedings verbessern

thesis_main.tex
Sammelwerke werden so auch mit nur einer Referenz angezeigt gem. Leitfaden und eine "einfachere" Aufteilung des Literaturverzeichnisses.
=> Sammelwerk & Literaturdarstellung

README.md, thesis_main.tex
JavaScript wird als Syntax-Highlighting von Listings nicht unterstützt.
Man kann es jedoch, wie hier geschehen, selbst implementieren.
=> Add JavaScript Highlighting

.travis.yml
At the moment, travis do not fail because of the exit code of docker-compose. This change takes the exit code of the fom container.
=> Change travis exit code

Dockerfile, thesis_main.tex
Hallo zusammen,
kompiliere ich eine Datei mit den letzten Änderungen (Also auch LuaLatex) in Visual Studio Code, so werden Umlaute nicht mehr korrekt dargestellt. Aus "ß" wird z.B. "SS".
Das scheint am Befehl \usepackage[T1]{fontenc} zu liegen. Das Paket fontenc ist inkompatibel mit LuaLatex. Wird der Befehl entfernt führt das stattdessen zu einer falschen Schriftart.
Bei mir hilft es das Paket luaiputenc einzubinden. Wird z.B. hier auch empfohlen:
https://texfragen.de/was_muss_ich_beim_umstieg_auf_luatex_beachten
Mir erschließt sich allerdings nicht ganz, wie die aktuelle PDF so überhaupt entstehen konnte. @ChristianLuxem kannst du ohne den Merge hier mit LuaLatex ein PDF kompilieren?
Ansonten prüft bitte gerne alle einmal, ob es so für euch funktioniert.
Danke.
EDIT: Gerade gesehen: …
=> Umlaute mit LuaLatex

skripte/modsBiblatex2018.tex
Hiermit wird das Leerzeichen vor urltime nur noch dann eingefügt, wenn dieses Feld gefüllt ist.
=> Leerzeichen bei fehlendem urltime

thesis_main.tex
Durch den Zeilenumbruch, bzw. das Einrücken ist mehr als ein Leerzeichen zwischen den Worten. Siehe Issue #141
=> Abstand zwischen Hochschulzentrum und Städtename

thesis_main.tex
Moin,
laut Leitfaden ist der Sperrvermerk "dem Textteil voranzustellen [...] und nach den Verzeichnissen vor dem Text folgt".
Entsprechend muss er verschoben werden.
Da der Sperrvermerk im PDF nicht angezeigt wird spare ich mir das neu kompilieren.
=> Sperrvermerk an falscher Stelle

kapitel/anhang/sperrvermerk.tex
Bisher wurde das Datum nicht automatisch eingetragen, sowie die Unterschrift nicht eingefügt.
Das passiert jetzt im selben Format wie in der ehrenwörtlichen Erklärung. (Ist 1:1 kopiert)
=> Datum und Unterschrift in Sperrvermerk

literatur/literatur.bib, thesis_main.tex
Durch den Wechsel der Zeilen meldet Latex die folgende Fehlermeldung nicht mehr:
Package csquotes Warning: Load 'inputenc' before 'csquotes' on input line 308.
Übersetzung funktioniert weiterhin
=> Latex Warning ausgebaut

skripte/modsBiblatex2018.tex, thesis_main.tex
thesis_main.tex und modsBiblatex2018.tex angepasst, um ibid Fussnoten (Ebd. statt sich wiederholender Quellen) zu unterstützen. Die Umstellung auf Ibid erfolgt in \usepackage[...]{biblatex} in der thesis_main.tex durch:
- Auskommentieren von: %style=ext-authoryear-ibid
- Kommentieren von: style=ext-authoryear-ibid
Weiterhin \hypersetup in der thesis_main.tex um citecolor=darkblack erweitert, um grüne Fussnoten zu verhindern (falls diese in das Quellenverzeichnis linken). Thanks to https://tex.stackexchange.com/a/847/231830
This issue resolves #151
=> Ibid Fussnoten

Dockerfile, compile.sh
- use Ubuntu 20.04 as base image
- only use tex-live packages from the Ubuntu repos
- replace `texlive-generic-extra` with `texlive-plain-generic` because the former is not available anymore in Ubuntu 20.04
- export the `$TERM` environment variable in the `compile.sh` script, as it lead to a warning because it was not set
Was there a particular reason to add that `texlive-2018` to the sources? Could removing it lead to breaking something?
=> Update Dockerfile, avoid $TERM warning

thesis_main.tex
Präfix in das Abbildungs- und Tabellenverzeichnis aufnehmen, statt nur der Nummerierung (siehe Issue #206)
=> Präfix im toc und tof hinzugefügt

thesis_main.tex
Bug
When working with `\addcontentsline`, hyperref needs a `\phantomsection` to align the hyperref correctly.
Dieser Fehler ist mir kurz vor Abgabe meiner Arbeit selber aufgefallen.
=> :bug: Fix hyperref not linking to table of abbreviations correctly

compile.sh, countwords.sh
bug
This fix bash specific error in word count script and make wordcount.sh executable.
Error message:
```
./countwords.sh: 14: [: y: unexpected operator
./countwords.sh: 14: [: y: unexpected operator
./countwords.sh: 14: [: y: unexpected operator
./countwords.sh: 14: [: y: unexpected operator
```
Details under: https://stackoverflow.com/questions/20449543/shell-equality-operators-eq
Fixes #
=> make wordcount executable and set syntax to bash

compile.sh
bug
- Einführung einer `cleanup`-Funktion zur Entfernung temporärer Dateien.
- Automatisches Löschen der bestehenden PDF-Datei vor dem Kompilierungsprozess.
- Aufruf der `cleanup`-Funktion sowohl vor als auch nach dem Kompilieren.
Diese Anpassungen beheben das wiederkehrende Problem, bei dem nach Korrektur einer beschädigten `.bib`-Datei weiterhin Fehler aufgrund veralteter temporärer Dateien auftraten. Durch die verbesserte Bereinigung wird sichergestellt, dass der Kompilierungsprozess nicht durch alte, fehlerhafte Hilfsdateien gestört wird.
* Where does the change come from? The motivation?
Nach der Korrektur fehlerhafter `.bib`-Dateien traten weiterhin Kompilierungsfehler auf, verursacht durch veraltete temporäre Dateien. Diese führten zu zeitaufwändiger Fehlersuche, obwohl die …
=> **fix:** Bereinigung temporärer Dateien nach Bibliographie-Fehlern

kapitel/kapitel_2/kapitel_2.tex, literatur/literatur.bib
Im Leitfaden von Januar 2024 steht:
```
Um den Fußnotenapparat übersichtlich zu gestalten, kann in den Fällen, in denen sich
drei Verfasser oder mehr für einen Beitrag verantwortlich zeichnen, auf die komplette
Nennung der Verfasser in den Fußnoten (nicht im Literaturverzeichnis!!!) verzichtet wer-
den. Stattdessen beschränkt sich die Angabe auf den Namen des zuerst genannten Ver-
fassers mit dem Zusatz „et al.“ (= et alii) oder auch „u. a.“ (= und andere).
```
Dies entspricht nicht mehr der Beschreibung in der Datei 
https://github.com/andygrunwald/FOM-LaTeX-Template/blob/d8a32adf75f4dd65be7cd2b24fddf7b505608114/kapitel/kapitel_2/kapitel_2.tex#L113-L119
Diese PR vebessert den Inhalt des 4 Jahre alten Kapitels.
Die Anmerkung `(nicht im Literaturverzeichnis!!!)` könnte durch die in den …
=> Update zur aktuellen Version des Leitfaden jan 2024
