literatur/literatur.bib
Beispiel hinzugefügt, wie ein Online-Eintrag in der Bibliothek angelegt werden soll.
Da wir hier Wirtschaftsinformatik studieren, werden wohl einige Online-Quellen benutzen..
=> Beispiel für Online-Einträge hinzugefügt

skripte/modsBiblatex.tex
See also my Issue from may `16
=> Authors weren`t displayed

Dockerfile, README.md
Hi @andygrunwald,
hier meine angekündigten Vorschläge. 
Die Formatierung ist natürlich Geschmackssache. Daher bin ich Dir nicht böse, wenn Du den PR schließt ;-)
Vorher:
```
$ docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
andygrunwald/fom-latex-template   latest              2c37392e30f0        7 seconds ago       731.4 MB
```
Nachher:
```
$ docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
andygrunwald/fom-latex-template   latest              fa031cd3afcf        18 seconds ago      674.8 MB                                                                                                              
```
=> Update Dockerfile and documentation

thesis_main.tex
small pr to remove a duplicate \usepackage of colortbl
=> remove duplicate package usage of colortbl

README.md
Issue: https://github.com/andygrunwald/FOM-LaTeX-Template/issues/84
Inhalt:
- Einheitliche Schriftarten erzwingen
- Anpassungen im Inhaltsverzeichnis
=> Einheitliche Schriftarten erzwingen

.vscode/settings.json, README.md, kapitel/einleitung/einleitung.tex
Habe mal noch Visual Studio Code als IDE hinzugefügt :) 
Grüße
Daniel
=> added new IDE -> Visual Studio Code with settings

.vscode/settings.json
This Pull request removes the forgotten statement mentioned in #128 .
=> Remove forgotten statement

skripte/modsBiblatex2018.tex, thesis_main.tex
Für mehr Infos am besten #152 ansehen :-)
Danke @Servior85 fürs bescheid sagen. Ich hoffe das behebt es bei Dir auch.
=> Behebt die URL in der Online-Literatur

kapitel/titelseite.tex, thesis_main.tex
Die Martikelnummer wurde in Englisch nicht richtig angezeigt.
=> Extract titelseite and fix marticulation number

README.md, thesis_main.tex
Ich hatte diese Möglichkeit entdeckt, als ich mit dem Projekt beschäftigt habe. Habe hierzu folgenden Issue erstellt https://github.com/andygrunwald/FOM-LaTeX-Template/issues/164 
und ich konnte damit bereits jemand anderes heflen
@Steffeeeen1234 ja, großen Dank dir!mich 
_Originally posted by @upelham in https://github.com/andygrunwald/FOM-LaTeX-Template/issues/153#issuecomment-653864577_ 
Daher sah es für mich nach einer möglichen guten Änderung aus.
=> Einfacheres Kompilieren in die englische Sprache

README.md
Wer kein Docker mag, kann über WSL eine Linux-Installation unter Windows 10 nutzen.
=> Windows Subsystem for Linux (WSL)

README.md, thesis_main.tex
Tippfehler in README bereinigt
=> Refactoring, Typos fixed, Hint to LTeX in Readme added

kapitel/kapitel_2/kapitel_2.tex
Hiermit kommen noch ein paar Beispiele für das Formel und Symbolverzeichnis.
Damit sollte der Issue #179 geschlossen sein.
=> Weitere Informationen für das Formel und Symbolverzeichnis

README.md
I have reworked and shortened the Disclaimer a bit to make it a bit more clear what it means to use this template.
=> Rework of the Disclaimer

.github/FUNDING.yml
"feature"
Wir nutzen hier [GitHub Sponsors](https://github.com/sponsors).
Dies fügt einen Sponsoring-Button zum Projekt hinzu.
Vielleicht findet sich der ein oder andere ja, der uns etwas finanziell für einen Kaffee oder eine Pizza supporten will.
@ChristianLuxem @SimonHaak @Steffeeeen1234: Leider hat von euch keiner GitHub Sponsors aktiviert. Wenn ihr das macht, könnt ihr gerne euren Username zur Liste hinzufügen.
None
None
=> Informationen um das Projekt zu supporten

README.md, thesis_main.tex
documentation
Line 142 falsch kommentiert
https://github.com/andygrunwald/FOM-LaTeX-Template/blob/b38a6332a8e48972985016ca2a99dc793d330960/thesis_main.tex#L142
`style=ext-authoryear-ibid`:  "ebd." für sich wiederholende Fußnoten
`style=ext-authoryear`: **ohne** "ebd." für sich wiederholende Fußnoten. Voll ausgeschrieben.
Ist momentan genau falsch herum kommentiert.
Fixes #
=> Kommentar zur Nutzung von ebd. (ebenda) korrigiert

README.md
`\` vor `usepackage[` hinzugefügt.
Fixes #
=> Slash in Zeile 156 hinzugefügt

kapitel/vorwort/vorwort.tex
=> Vorwort; Variablen ergänzt

thesis_main.tex
feature
Ergänzung der Silbentrennung laut Leitfaden. Damit Endet fast jeder Blocksatz ohne jegliche Trennung.
Lieber Andy, vielen Dank für dieses super Template! Mein Beitrag dazu.
=> Added hyphenation per style guide to ensure justified text without breaks

skripte/modsBiblatex2018.tex
bug
Es entfernt "Zugriff" von Nicht-Online-Inhalten
Fixes #244
=> Entferne Zugriff von Nicht-Online-Inhalten

README.md, thesis_main.tex
feature
Dieser Pull Request erweitert die Vorlage um die Funktion des Wordcounts in Overleaf.
none
Die Dokumentation des Wordcounts in Overleaf ist unter folgendem Link verfügbar:
https://www.overleaf.com/learn/how-to/Is_there_a_way_to_run_a_word_count_that_doesn%27t_include_LaTeX_commands%3F
=> added Overleaf wordcount

README.md
Documentation
This Request adds the instructions for the nightly buildes as described in Issue #234 to the README.md so that users can fix that issue easily
Fixes #234 
I myself have found me encountering that issue in the third project based on this template now. Every time I search for the solution in the issues and added this so that it's easier for others to find.
Maybe it needs a little rewording, that I'm not really sure of.
=> :memo: Implementing instructions described in #234
